version: "3.8"
services:

  postgres:
    image: postgres  
    restart: always  
    environment:  
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: root  
      POSTGRES_DB: rickandmortyapp  
    ports:  
      - "5440:5432"  